name: frikandel_special999
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.4
  firebase_core: ^2.31.0
  firebase_storage: 11.7.5
  firebase_analytics: ^10.0.2
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  permission_handler: ^10.0.0
  image: ^3.0.1
  intl: any
  url_launcher: any
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
