// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9_oGxAdYuyU06bA_wVZPPfCSRM3P-XrQ',
    appId: '1:202910744709:web:a86db0d9cd0a82ddf0e9ec',
    messagingSenderId: '202910744709',
    projectId: 'frikandelspecial999',
    authDomain: 'frikandelspecial999.firebaseapp.com',
    storageBucket: 'frikandelspecial999.appspot.com',
    measurementId: 'G-W81BK0CTC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0iC0-cH-MsdSotYp9Ciazc_6Avhz7FoU',
    appId: '1:202910744709:android:2953214ec70a1b9ef0e9ec',
    messagingSenderId: '202910744709',
    projectId: 'frikandelspecial999',
    storageBucket: 'frikandelspecial999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmmEpKTdYIjar3DfGORZZbL87Ibp4cu5s',
    appId: '1:202910744709:ios:e6ec9e3559527344f0e9ec',
    messagingSenderId: '202910744709',
    projectId: 'frikandelspecial999',
    storageBucket: 'frikandelspecial999.appspot.com',
    iosBundleId: 'com.example.frikandelSpecial999',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmmEpKTdYIjar3DfGORZZbL87Ibp4cu5s',
    appId: '1:202910744709:ios:e6ec9e3559527344f0e9ec',
    messagingSenderId: '202910744709',
    projectId: 'frikandelspecial999',
    storageBucket: 'frikandelspecial999.appspot.com',
    iosBundleId: 'com.example.frikandelSpecial999',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9_oGxAdYuyU06bA_wVZPPfCSRM3P-XrQ',
    appId: '1:202910744709:web:67e9bdde9fe13c01f0e9ec',
    messagingSenderId: '202910744709',
    projectId: 'frikandelspecial999',
    authDomain: 'frikandelspecial999.firebaseapp.com',
    storageBucket: 'frikandelspecial999.appspot.com',
    measurementId: 'G-0YXQ3C8C22',
  );

}